import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import CustomNavbar from "@/components/CustomNavbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <CustomNavbar/>
     <div className="mt-2">
     {children}
     </div>
       
        <Footer/>
        </body>
    </html>
  );
}
